require 'bundler/setup'
require 'rubygems'
require 'capistrano'
require 'xp5k'
require 'erb'
require 'colored'

load "config/deploy.rb"

# We define a automatic task 
# to start the deployment
desc 'Automatic deployment'
task :automatic do
 puts "Welcome to automatic deployment".bold.blue
end

# We chain with the other main tasks
after "automatic", "xp5k", "setup", "openstack"
